### ISSUE TITLE
Change Japanese phrase to English

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-SimpleCorporate#1]
Also, make a L10N.

**Comment by yuji** [comment]
done

**Comment by yuji** [comment]
@crawl749 @cmatsuo 

英語化と日本語対応いれました。
ディレクトリ名の大文字を小文字に直しているので、Clone していない場合は、一度手元のテーマを削除してもらった方がいいかもしれない。

**Comment by crawl749** [comment]
確認できたのでクローズ
