### ISSUE TITLE
カテゴリ選択後、プルダウンメニューが、表示しているアーカイブのカテゴリ名ではなく、「ニュース」になっているのが気持ち悪い

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#10]
できれば、選択している名前が表示されていてほしい。

![catmenu](https://cloud.githubusercontent.com/assets/546386/21340170/18b2c516-c6c8-11e6-886e-9c2c8945a945.jpg)

**Comment by wtnbtkfm** [comment]
@cmatsuo 
上記のキャプチャでいうところの、ニュースとなっているところが「東京ディズニーランドホテル」になればよいですか？
また、このキャプチャはカテゴリーアーカイブだと思いますが、年別アーカイブや記事詳細も変えたほうがよいですか？

**Comment by cmatsuo** [comment]
@wtnbtkfm 
はい、上記で言えば「東京ディズニーランドホテル」ですね。

このテーマのデフォルトでは「年別アーカイブ」にプルダウンメニューは無いと思うのですが、ご質問はどこの表示にあたりますか？同様に、「記事詳細も」。

**Comment by wtnbtkfm** [comment]
@cmatsuo 

年別アーカイブは以下キャプチャの赤枠部分です。
![yearly](https://cloud.githubusercontent.com/assets/8991793/21490090/1c47ec94-cc34-11e6-8923-2ca6445b7b89.png)

記事詳細は以下キャプチャの赤枠部分です。
![entry](https://cloud.githubusercontent.com/assets/8991793/21490146/a944f858-cc34-11e6-8d78-c1c4fe829705.png)

ちょっと整理させていただきたいのですが、
松尾さんのご意見としては、カテゴリアーカイブのページだけヘッダーの赤枠の「ニュース」がカテゴリ名になっているべきで、それ以外のページ（年別アーカイブ、記事詳細、ウェブページ）などは「ニュース」のままになっていた方が良い。
で間違いありませんか？

**Comment by cmatsuo** [comment]
@wtnbtkfm 
あー、もしかして。カテゴリ選択メニューを、選択したカテゴリを表示したままの状態にするのって、かなり大変です？

**Comment by wtnbtkfm** [comment]
@cmatsuo 
選択したカテゴリを表示したままの状態にするのは難しくはないのですが、カテゴリーアーカイブだけ「ニュース」がカテゴリ名になるのは少々違和感があるかなと。

**Comment by cmatsuo** [comment]
あー、そうか。記事ルート＝「ニュース」カテゴリ下と思えばいいのか。気持ち悪いけど、手を打ちます。
