### ISSUE TITLE
TOPを選択すると、カテゴリの無い記事の一覧になるのが気持ち悪い

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#11]
プルダウンメニューの「TOP」を選択すると、感覚的にはブログのトップページへ移動することを期待すると思うのですが、このテーマでは、カテゴリの無い記事のアーカイブに移動します。左隣にあるリンクでトップページに行けるとは言え、わかりにくい。

![top](https://cloud.githubusercontent.com/assets/546386/21340247/9fd8d35a-c6c8-11e6-9ab8-50eefaa8a06b.jpg)

**Comment by wtnbtkfm** [comment]
@cmatsuo 
ニュース配下の「TOP」はニュースのTOPに戻れるべきだと思います。
ブログTOPへのリンクに変えるとその左の「TOP」と内容が重複してしまいますし、あまりよろしくないかと。
ですので、リンク先を変えるよりも「TOP」を「ニュース TOP」などに変える方がベターかなと思うのですが、いかがでしょうか？

**Comment by cmatsuo** [comment]
@wtnbtkfm 
いや、カテゴリを設定していない記事がMTに勝手に「TOP」というカテゴリに入れられているような感じがするのが気持ち悪いのです。TOPの代わりに「uncategorized」となっていれば違和感はありませんが、それではメニューとしておかしいですよね。
また、「ニュースTOP」と表示されると、カテゴリに関係なくすべての記事アーカイブが表示されて欲しいですが、いかがでしょう？（このテーマでは、カテゴリや公開年と関係なくすべての記事アーカイブが新しいものから順に表示される画面はないので、そういった表示も「あり」かと思えます）

**Comment by wtnbtkfm** [comment]
@cmatsuo 
そもそもの問題としては「ニュース」をクリックするとドロップダウンが開くだけで、ニュースのTOPの導線にはなっていない、というところにあるような気がしますね。
このテーマはカスタマイズ性を考慮してcssフレームワークとしてBootstrapを採用しているのですが、Bootstrapのドロップダウンメニューの仕様的に「ニュース」をニュースのTOPへの導線として使えないのが頭の痛いところです。。。

松尾さんの仰る
> また、「ニュースTOP」と表示されると、カテゴリに関係なくすべての記事アーカイブが表示されて欲しいですが、いかがでしょう？（このテーマでは、カテゴリや公開年と関係なくすべての記事アーカイブが新しいものから順に表示される画面はないので、そういった表示も「あり」かと思えます）

こちらは私も全くの同意見なのですが、記事が多くなった時に記事が全て並んでいると縦に長くなりすぎて閲覧しづらいと思われるのと、.netと違い基本的にページ分割（ページャーをつける）は出来ないので、何が最善かを検討する必要がありそうです。
ページ分割に関しては、静的分割ならプラグイン（Pagebute）を使う、動的分割ならjsでページを分割するようなコードを書く、という方法もありますが、配布するテーマで外部のプラグインが必須だというのはどうなのか？とか、jsでページを分割するのはseo的な観点やユーザビリティー的にどうなのか、など議論する必要がありそうです。

本件は少々こちらで揉みますのでお時間を下さい。
進捗ありましたらご報告します。

**Comment by cmatsuo** [comment]
了解です。よろしくお願いします。

**Comment by cmatsuo** [comment]
@wtnbtkfm 
これまだお知らせないですが、最新記事10件が表示されるように修正してくれました？

**Comment by wtnbtkfm** [comment]
@cmatsuo 

> これまだお知らせないですが、最新記事10件が表示されるように修正してくれました？

こちらですが、ニュースTOPページのことで間違いありませんか？
ニュースTOPページは特にテンプレート側で何かをしているわけではありませんが、
設定　＞　全般　＞表示される記事数
で設定されている記事数が表示されるはずです。
デフォルトでは10になっているので、現状10件だけ表示されます。

**Comment by cmatsuo** [comment]
@wtnbtkfm 
分かりにくい書き方だったようですみません。
上のほうで書いたように、以前は、カテゴリ指定のされていない記事10件が表示されていた状態だったのが、コメントを書いた時点で、カテゴリの有無にかかわらず最新記事10件の表示に変わっていたので、そのように修正していただけたのかな、クローズしてもいいかな…という確認をしようと書いたものでした。

というわｋで、現状の、最新記事10件が表示される状態が分かりやすいと思います。そういう仕様に変更になったという認識で、クローズしてよろしいでしょうか？

**Comment by wtnbtkfm** [comment]
@cmatsuo 
はい。そのご認識で間違いありません！
クローズお願いします。

**Comment by cmatsuo** [comment]
クローズ！
