### ISSUE TITLE
シークレットタグをつけてもサイトロゴが差し替わらない

### ISSUE THREAD

**Issue by crawl749** [movabletype/mt-theme-SimpleCorporate#12]
headerテンプレートの以下部分
> <mt:if name="site-logo"><mt:assets tag="@SITE_LOGO" limit="1"><mt:assetthumbnailurl></mt:assets></mt:if>
>       <a href="<mt:blogrelativeurl>" class="brand"><mt:if name="site-logo"><mt:assets type="image" tag="@SITE_LOGO" limit="1"><img src="<mt:assetthumbnailurl>" alt="<mt:blogname>"></mt:assets><mt:else><img src="<mt:blogrelativeurl>images/logo.png"></mt:if></a>

MTで画像をアップし、@SITE_LOGOをつけても、見に行くのは
> <imgsrc="<mt:blogrelativeurl>images/logo.png">

の画像です。

試しに

> <mt:assets type="image" tag="@SITE_LOGO" limit="1"><img src="<mt:assetthumbnailurl>" alt="<mt:blogname>"></mt:assets>

とテンプレートに書いて出力したところ、@SITE_LOGO指定している画像が表示されました。
シークレットタグは動作しているように思うので、タグを見直していただけると。。

**Comment by wtnbtkfm** [comment]
@crawl749 
こちらも正常にsetvar出来ていない不具合がありました。
修正しpushしましたので再度ご確認頂けると助かります。

**Comment by crawl749** [comment]
修正確認できたのでクローズします。
