### ISSUE TITLE
フォルダ＆ページ→最近の記事の表示順は逆のほうがいいのでは

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#13]
TOPページのヘッダー下のコンテンツの部分について、フォルダとページ→最近の記事という流れではなくて、最近の記事のボックスとしたほうが、利用例を示すテーマとして分かりやすいのではないでしょうか？

![order](https://cloud.githubusercontent.com/assets/546386/21341711/286e9c10-c6d1-11e6-8d69-27bb502cb02b.jpg)

**Comment by wtnbtkfm** [comment]
@cmatsuo  @terukick 

本テーマは
「MTのフォルダ機能やウェブページ機能をフル活用する」
ということがコンセプトの１つとしてあるので、個人的にはこのままの構成で良いかな、と思っていま
すがいかがでしょうか。

コンセプトなどのついては特にお伝え出来ていませんでしたね。申し訳ありません。

**Comment by terukick** [comment]
@cmatsuo
>「MTのフォルダ機能やウェブページ機能をフル活用する」

という意味では渡辺君の言う様に、僕もブログ記事のリストよりもフォルダやウェブページがメインコンテンツになっている方が良いと思います。

**Comment by cmatsuo** [comment]
そういうコンセプトがあったのですね。なるほど。
