### ISSUE TITLE
footer_link 仕様確認

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#14]
仕様に以下のような記述がありますが：

 * フッター右にはの説明フィールドに「footer_link」と入力されているフォルダ配下のウェブページの一覧リンクが出力されます。

この footer_link を使った場合、ヘッダーおよび、トップページでのコンテンツの中央部分への該当のフォルダおよびページの表示がなくなることについては、記述がありません。
仕様でしょうか、バグでしょうか？

**Comment by wtnbtkfm** [comment]
@cmatsuo 
これは仕様です。
例えばヘッダーのリンクを出力する箇所は
`<mt:unless name="description" eq="footer_link">`
この記述でリンクを出力しないようにしています。

記載漏れですので、後ほど追記しておきます。

**Comment by cmatsuo** [comment]
了解です！
