### ISSUE TITLE
記事、ページの追記が表示されない

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#15]
記事、ページの追記に入力しても、記事アーカイブ、ページアーカイブにも入力内容が表示されない。

**Comment by crawl749** [comment]
.netのテンプレには<$mt:EntryMore$>と<$mt:PageMore$>はあった。

**Comment by wtnbtkfm** [comment]
@crawl749 
記事詳細に追記が反映されるように修正しました。
昨日pushした分に含まれていますので、改めてpullって頂く必要はありません。
ご確認お願いします。

**Comment by cmatsuo** [comment]
記事、ページとも追記が表示されるようになったことを確認しました！
