### ISSUE TITLE
アーカイブやインデックスでの表示数はどうやってコントロールするのか

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#16]
.net版では、configに記述してアーカイブでの表示数を設定できるようにしているようですが、仕様および、MT版でいただいたパッケージにはそのような記述はありません。

管理画面にある表示記事数の設定も関係ないようですが、MT版の仕様としてはどうなりますか？

**Comment by wtnbtkfm** [comment]
@cmatsuo 
.netの方は少々独自進化しているようで、MT版にはその機能は実装されていません。
実装するかを少々検討させていただきたいと思うので、少々お時間を下さい。
進捗があったら改めてご報告します。

**Comment by cmatsuo** [comment]
よろしくお願いします！

**Comment by wtnbtkfm** [comment]
@terukick 

本件ですが、加藤さん的にはいかがでしょうか？
表示数を設定できるようにするということは、ページ分割機能を実装するということとほぼイコールだと思うので、ソフトウェア版のテーマではちょっと厳しいなと思っています。
ちなみに.netはページ分割機能がついています。

ソフトウェア版でページ分割を実装する場合、pagebuteなどのプラグインを使うのが一般的にだと思うのですが、SAが配布するテーマでサードパーティーのプラグインが必須というのはどうなのかな？と個人的には思います。

**Comment by terukick** [comment]
@wtnbtkfm 
pagebuteを入れるのは無しな気がしますので、現状ママで良いかと思います。

**Comment by cmatsuo** [comment]
表示数のコントロールはせず、アーカイブ一覧は全表示、という仕様で了解です。
