### ISSUE TITLE
【質問】フォルダの編集の背景画像について

### ISSUE THREAD

**Issue by crawl749** [movabletype/mt-theme-SimpleCorporate#17]
<img width="532" alt="fldr" src="https://cloud.githubusercontent.com/assets/546365/21412043/6fd11f50-c830-11e6-91b0-f56693e75721.png">

ここなんですが、この画像はどこに表示されるものなのでしょうか？
現状、画像をアップしてもどこにも表示されているように見えないです。

**Comment by wtnbtkfm** [comment]
@crawl749 
途中まで実装して結局採用されなかったものが残ってしまっていたようなので、カスタムフィールド自体を削除しました。
pushしてありますのでご確認よろしくお願いします。

**Comment by crawl749** [comment]
修正確認できたのでクローズします。
