### ISSUE TITLE
【質問】クリエイティブ・コモンズについて

### ISSUE THREAD

**Issue by crawl749** [movabletype/mt-theme-SimpleCorporate#18]
@wtnbtkfm 

Simple Corporateにはクリエイティブ・コモンズを設定してもどこにも表示されません。
意図的に外したのだとしたら、理由を教えていただけるとうれしいです。
（他のテーマには全てCCが表示されるようになっています）

**Comment by wtnbtkfm** [comment]
@crawl749 
なるほど。完全に盲点でした。。。
今後のためにちょっと確認させていただきたいのですが、SAが配布するテーマは基本的にCCのライセンス、ということで間違いないですか？
基本的にCCである、とうことであれば以降作成するテーマには必ず設定しようと思います。

**Comment by yuji** [comment]
@wtnbtkfm 
MTのテーマがというより、MTの管理画面でCCライセンスの設定を行うことができ、それをウィジェットなどで表示する仕組みがない。ということかと。

**Comment by cmatsuo** [comment]
@wtnbtkfm 
高山さんの書いている通り、テーマのCCではなくて、このテーマを使ったユーザーがMTでCCを設定しても、表示されるようになっていない、という意味ですね。

**Comment by wtnbtkfm** [comment]
@yuji  @cmatsuo 
承知しました。
今後作成するテーマは全て、管理画面でのCCライセンスの設定を行うことが出来るようにする。ということで進めます！
修正完了後、改めてご報告します。

**Comment by wtnbtkfm** [comment]
@crawl749 
本件ですが、現行バージョンのMTでCCライセンスの設定が保存されないというバグが発生しているようです。
これが解消されないと中々実装も出来ませんので、こちらは一旦保留にさせてください。

**Comment by yuji** [comment]
https://movabletype.fogbugz.com/f/cases/114356/

**Comment by crawl749** [comment]
@wtnbtkfm 
修正が入りまして、表示されるようになりました。
高山さんがパッチを用意するとのことなので、保留解除でお願いします。

@yuji
パッチよろしくお願いします。

**Comment by yuji** [comment]
@wtnbtkfm 

https://github.com/movabletype/movabletype/blob/1508125cf40db975272f9c978836941eb103f610/tmpl/cms/cfg_prefs.tmpl

MT_HOME/tmpl/cms/cfg_prefs.tmpl を上記ファイルと差し替えればOK
オリジナルはリネームしておくといいよ。

**Comment by wtnbtkfm** [comment]
@yuji 

ご対応ありがとうございます！
やってみます。

**Comment by wtnbtkfm** [comment]
@yuji 

ライセンスが保存されることを確認しました。
ありがとうございました！

**Comment by wtnbtkfm** [comment]
@crawl749 

管理画面のライセンスの設定が反映されるように修正しました。
フッターの右下に表示されます。
ご確認お願いします。

**Comment by crawl749** [comment]
確認できたのでクローズ
