### ISSUE TITLE
BlogDescriptionの表示内容が混線している

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#19]
以下、全般設定の「説明」、および、インデックスページテンプレートの「meta description」、ニュース TOPテンプレートの「meta description」のすべてにそれぞれ説明文を入力した際の、ソースの抜粋です。

実際の表示：
* ブログのトップ
`<meta name="description" content="インデックスページテンプレートのブログの説明管理画面で設定したブログの説明">`

* ニュースTOP
`<meta name="description" content="ニュースTOPのブログの説明管理画面で設定したブログの説明">`

* 個別アーカイブ
`<meta name="description" content="">`

期待する表示：
* ブログのトップ
`<meta name="description" content="インデックスページテンプレートのブログの説明">`

* ニュースTOP
`<meta name="description" content="ニュースTOPのブログの説明">`

* 個別アーカイブ
`<meta name="description" content="管理画面で設定したブログの説明">`

**Comment by wtnbtkfm** [comment]
@cmatsuo 
仰るとおり色々と不具合がありましたので以下の通り修正しました。
カスタムフィールドに入力されていない場合の分岐などを整理しています。

ブログのトップ
・トップのインデックステンプレートのカスタムフィールドに入力されている場合

`<meta name="description" content="トップのインデックステンプレートのカスタムフィールドに入力されている文言">`

・トップのインデックステンプレートのカスタムフィールドに入力されていない場合

`<meta name="description" content="ブログの説明文（mt:blogdescriotion）">`


ニュースTOP
・ニュースTOPのインデックステンプレートのカスタムフィールドに入力されている場合

`<meta name="description" content="ニュースTOPのインデックステンプレートのカスタムフィールドに入力されている文言">
`
・ニュースTOPのインデックステンプレートのカスタムフィールドに入力されていない場合

`<meta name="description" content="ブログの説明文（mt:blogdescriotion）">`


個別アーカイブ
・記事のカスタムフイールド「記事用 meta description」に入力されている場合

`<meta name="description" content="「記事用 meta description」に入力されている文言">`

・記事のカスタムフイールド「記事用 meta description」に入力されていない場合

`<meta name="description" content="ブログの説明文（mt:blogdescriotion）">`

ご確認宜しくお願い致します。

edit20170-01-13 10:40  上記、コード部分が表示されないため、勝手ながら編集しました（by cmatsuo）

**Comment by cmatsuo** [comment]
上記について、期待通りに動作するようになったことを確認しました。

@wtnbtkfm 
ページアーカイブについて報告漏れがありました。こちらもよろしくお願いします

* ウェブページ用 meta description に入力されている（ブログの設定画面にも説明が入力されている）場合：

`<meta name="description" content="ウェブページ用 meta description <a href="http://sixapart.jp">6a.jp</a>ブログの管理画面で設定したブログの説明6a.jp">`

* ウェブページ用 meta description に入力されていない（ブログの設定画面には説明が入力されている）場合：

`<meta name="description" content="">`

**Comment by wtnbtkfm** [comment]
@cmatsuo 

ウェブページアーカイブも修正しました。

・ウェブページ用 meta description に入力されている（ブログの設定画面にも説明が入力されている）場合：
<meta name="description" content="ウェブページのカスタムフィールドに入力されている文言">

・ウェブページ用 meta description に入力されていない（ブログの設定画面には説明が入力されている）場合：
<meta name="description" content="ブログの説明文">

となるように修正してあります。
ご確認よろしくお願いします。

**Comment by cmatsuo** [comment]
修正を確認。
