### ISSUE TITLE
imgが表示されない

### ISSUE THREAD

**Issue by crawl749** [movabletype/mt-theme-SimpleCorporate#2]
インデックステンプレート37行目あたりの
`<h2><img src="/movabletype/simplecorporate/asstes/images/main-img.png" alt=""></h2>`

MTには該当パスがないため、壊れた画像アイコンが出ます。
パスを変える必要or消す必要があるかと思うのですが。。
どう思います？

<img width="1225" alt="simple_corporate" src="https://cloud.githubusercontent.com/assets/546365/21124603/46927b34-c123-11e6-9789-bd54a72c9c47.png">

**Comment by wtnbtkfm** [comment]
デフォルトの画像ファイルをテーマ適用時に自動でアップされるように修正しましたが、
別issueにてシークレットタグで運用できるように修正中です。
修正が完了しましたら改めてご報告します。

**Comment by crawl749** [comment]
@wtnbtkfm この件だけでいったら修正確認できているので、こっちは閉じちゃいますね。
