### ISSUE TITLE
使っていないシステムテンプレート

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#20]
SimpleCorporateでは、「ポップアップ画像」以外のシステムテンプレートは全く利用していないように見えるのですが、削除せずに残してあるのは、意図的なものでしょうか？

**Comment by wtnbtkfm** [comment]
@cmatsuo 
システムテンプレートは一回消してしまうと新規で作成することができないので、とりあえず残しています。システムテンプレートを削除してしまって、後からコメントや検索が必要になって困ったことが以前何度かありましたので。
とはいえ、残していることが正解とも思っておらず、正直どうして良いかわからないからとりあえず残している状態です。
こういう場合ですが、何かQA的な正解ってあったりしますか？

**Comment by yuji** [comment]
@wtnbtkfm @cmatsuo 
ご指摘の通り作成できるものではないので使う人は使う。使わない人は無視する。で良いと思います。

**Comment by cmatsuo** [comment]
@wtnbtkfm 
一応確認と思って聞いたのですが、まあ予想通りの返事をいただいたかんじ、ですかね。
特に正解とかいうのは無いです。ただ、サイドバーの「インクルードテンプレート」が全部エラー的な状態になるので、むしろ空テンプレートになってていてもいいのかも、と思いました。
