### ISSUE TITLE
ページでも概要が入力されていない時は本文を表示してほしい

### ISSUE THREAD

**Issue by crawl749** [movabletype/mt-theme-SimpleCorporate#21]
<img width="836" alt="simple_corporate" src="https://cloud.githubusercontent.com/assets/546365/21491935/8065a2b6-cc43-11e6-8321-a354f2999dc5.png">

添付画像のように「詳細を見る」が揃わず見栄えが悪いので、記事と同じく、ページの方でも概要が入力されていない時は本文を一部表示すべきかと。。

**Comment by wtnbtkfm** [comment]
@crawl749  @terukick 
「詳細を見る」が揃わずに見栄えが悪いという問題は、文章の長さに左右されるので本文の一部を表示するだけでは根本的に解決できないと思います。
スタイルを修正すれば文章の長さにかかわらずボタンの位置を統一することはできると思いますが、どうでしょうか？

**Comment by terukick** [comment]
@wtnbtkfm 
>スタイルを修正すれば文章の長さにかかわらずボタンの位置を統一することはできると思いますが、ど
うでしょうか？

その線で良いと思います。

**Comment by wtnbtkfm** [comment]
@crawl749 

こちらの見解としては、スタイルを見なおせば良いのでは、ということになったのですが、それでいかがでしょうか？

**Comment by crawl749** [comment]
@wtnbtkfm 
ではそれでお願いします。

**Comment by crawl749** [comment]
@terukick @wtnbtkfm 
それでお願いしますと言っておきながらなんですが、
MTPageExcerpt、MTPageBodyにwords="N"でN 文字分抜き出して表示される方がラクな気がするなと思ったのですがいかがでしょう？
ちなみに、entryの方もwords="N"つけたらいいんじゃないかと思ったのですが…

**Comment by terukick** [comment]
@crawl749 
それだとN文字より多い文章ばかりであれば高さは揃いますが、N文字より極端に少ないものがあると揃わないことになりそうですね。文字数を固定するのであれば、少なくとも2~3行分はあった方がよいとおもうので、1行分しかないものとかが出てきた時に困りそう。なので、上限を作るとしてもそれとは別にcssやJSで高さを制御した方が良いと思います。

**Comment by crawl749** [comment]
@terukick 
ある程度の高さはcssなりJSで制御しないとダメだとは思っているのですが、添付画像みたいになってしまうのもいかがなものかとか思うのですよ。
ちなみにこの画像はページではなく記事のほうですが。。
<img width="864" alt="0118112608" src="https://cloud.githubusercontent.com/assets/546365/22048534/06d60a1e-dd71-11e6-8db2-79adf82e65e7.png">

**Comment by terukick** [comment]
@crawl749 @wtnbtkfm 
ということは、最大文字数をMTで制御しつつ、スタイルで高さを揃えるというのが良さそうですね。

**Comment by crawl749** [comment]
と、おもいます。

**Comment by wtnbtkfm** [comment]
@crawl749 

以下のとおり修正しました。
・概要が入力されている場合は40文字抽出されて表示される。
・概要がない場合は本文がremove_htmlされた上で40文字抽出されて表示される
・「詳細を見る」ボタンは揃うようにスタイルを調整
・最新ニュースも同様に修正

ご確認お願いします。

**Comment by crawl749** [comment]
@wtnbtkfm 
ページの本文が出るようになったのは確認できたのですが、今度は概要が表示されなくなりました。。

**Comment by wtnbtkfm** [comment]
@crawl749 

概要と本文が両方入力してあるが、本文が表示されてしまう。ということで間違いないですか？

**Comment by crawl749** [comment]
@wtnbtkfm 
概要と本文が両方入力 > 本文表示
概要のみ > 何も表示されず
です。

概要と本文が両方入力されている場合は本文表示で問題ないですよね？

**Comment by wtnbtkfm** [comment]
@crawl749 
ご指摘の箇所ですが、TOPページのウェブページ一覧が表示される部分で間違いないですか？

**Comment by crawl749** [comment]
@wtnbtkfm 
そうです。
そちらでは表示されますか？

**Comment by wtnbtkfm** [comment]
@crawl749 

こちらの環境では問題なさそうです。
ちなみに概要と本文が両方入力されている場合は、概要が優先されて表示されるようにしてあります。

**Comment by crawl749** [comment]
@wtnbtkfm 
最新のテーマをpullってきましたが、
最新ニュース（記事）の方は問題なく、
概要と本文が両方入力されている場合は、概要が優先されて表示されていますが

ページの方は、概要のみの場合は何も表示されない、概要＋本文の場合は本文が表示されます。

**Comment by wtnbtkfm** [comment]
@crawl749 

むむ、、、おかしいですね。
こちらでは
・概要のみの場合は概要が表示される
・本文だけだと本文から40文字ほど抽出される
・概要＋本文だと概要が表示される
という風になっています。

「概要」と「ウェブページ用　meta description」を間違えているとかありませんか？

**Comment by crawl749** [comment]
@wtnbtkfm 

> 「概要」と「ウェブページ用　meta description」を間違えているとかありませんか？

それはないです。

最新のテーマをpullって2環境で確認してますが、どっちも同じ状態です。
こちらの手元のテーマのコードと見比べたいので、いつのcommitでどのテンプレートを修正したか教えていただけますか？

**Comment by wtnbtkfm** [comment]
@crawl749 

2017/01/31/ 14:40のコミットでindex_page.mtmlの60行目付近を修正しています。

**Comment by crawl749** [comment]
@wtnbtkfm

表示されなかった理由がわかりました。
テーマをあてた時に、概要というCFができるみたいで（ウェブページ用 / テキスト(複数行)）、そちらに入力していると概要は出ませんでした。
（出ない出ないと言っていたのは、そちらに入力していたせいでした。）
MTにもともとある「概要」に入力した場合は表示されました。

ということで、こちらのチケットはとじる事にしますが、
概要が2件あって紛らわしいので、その件についてはチケットを作成します。

**Comment by crawl749** [comment]
確認できたのでクローズ
