### ISSUE TITLE
フォルダ内ページ一覧のレイアウト崩れ

### ISSUE THREAD

**Issue by crawl749** [movabletype/mt-theme-SimpleCorporate#22]
<img width="1202" alt="simple_corporate" src="https://cloud.githubusercontent.com/assets/546365/21492076/a23e7268-cc44-11e6-8803-779c3c53fe1f.png">

添付画像のように、ページが増えるとレイアウト崩れが起きます。

**Comment by wtnbtkfm** [comment]
@crawl749 
テンプレートにバグがありました。修正しましたのでご確認お願いします。

**Comment by crawl749** [comment]
修正を確認したので閉じます
