### ISSUE TITLE
記事の属するカテゴリの表示

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#23]
記事に複数のカテゴリが設定されている場合、カテゴリアーカイブ、個別記事アーカイブ、年別アーカイブ等では、メインカテゴリのみでなく、設定したすべてのカテゴリを表示しても便利なのではないかと思うのですが、いかがでしょうか？

一例としてですが、添付は個別記事アーカイブの現在の表示です。赤枠の部分、横にいくつかカテゴリが並んでも、デザイン的にも問題ないように思います。

![category](https://cloud.githubusercontent.com/assets/546386/21494097/741f975a-cc52-11e6-8023-6b57800951ab.jpg)

**Comment by wtnbtkfm** [comment]
@cmatsuo 
仰るとおり、全てのカテゴリが表示されていた方が便利だと思いますので修正しました。
ご確認お願いします。

**Comment by cmatsuo** [comment]
修正を確認しました。
