### ISSUE TITLE
template_202.mtml をわかりやすい名称に変更

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-SimpleCorporate#24]
template_202.mtml だとなんのテンプレートか推測できないのでわかりやすい名称に変更願います。
themes.yaml 中の記述も。

**Comment by wtnbtkfm** [comment]
@yuji 

ちょっと教えてください！

このファイル名ですが、基本的には
モジュール名.mtml
で自動的にファイルが出力されるという認識で間違いないですよね？

今回template_202.mtmlになってしまっているテンプレートはsocial-buttonという名前のテンプレートモジュールなのですが、何か予約されている名前とぶつかって、結果template_202.mtmlになってしまっているということで間違いないでしょうか？

**Comment by yuji** [comment]
@wtnbtkfm 

identifier が指定されていないテンプレートは template_{template_id}.mtml という名前にしている模様。Export でベースを作ったらそこは直す。というワークフローになるね・・・。
なんて仕様だ・・・。

迷惑かけて申し訳ないけどもそういうことのようなので・・・。

**Comment by wtnbtkfm** [comment]
@yuji 

おお、理解しました！
では、以降はtemplate_{template_id}.mtmlになってしまっているテンプレートをチェックして、テーマの作成が一通り完了した段階でファイル名とtheme.yamlを修正する、というフローにしますー

**Comment by wtnbtkfm** [comment]
theme.yamlの中身を直接修正。templatesの中のファイル名を修正。
クローズします。
