### ISSUE TITLE
修正が終わったら最後にtheme.yamlを修正する

### ISSUE THREAD

**Issue by wtnbtkfm** [movabletype/mt-theme-SimpleCorporate#25]
毎回theme.yamlを修正するのが大変なので、issueがはけたら最後にサムネイルの設定などを行う。

**Comment by wtnbtkfm** [comment]
template_{template_id}.mtmlになってしまっているテンプレートがないかをチェックして、あったら修正する。

**Comment by cmatsuo** [comment]
@wtnbtkfm 
現在、再び以下のようなエラーが表示され、管理画面に入れない状態になっております。
theme.yamlの修正を先に行っていただくことはできませんでしょうか？

![themeyaml](https://cloud.githubusercontent.com/assets/546386/21914904/95524812-d979-11e6-8659-117c636fff88.jpg)

**Comment by wtnbtkfm** [comment]
修正が完了したのでクローズ
