### ISSUE TITLE
カスタムフィールドで作成する description の a タグなどを remove_html してください

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#26]
Steps:
1. ブログ＞全般設定＞ブログの説明に、「ブログの管理画面で設定したブログの説明<ahref="http://sixapart.jp">6a.jp</a>」を入力して保存。
2. 公開したブログインデックスのソースを参照:

`<meta name="description" content="ブログの管理画面で設定したブログの説明6a.jp">
`

3. ニュースTOPの meta description に、「ニュースTOPテンプレートで設定したブログの説明<a href="http://sixapart.jp">6a.jp</a>」を入力して保存。
4. 公開したブログのニュースTOP のソースを参照:

`<meta name="description" content="ニュースTOPテンプレートで設定したブログの説明<a href="http://sixapart.jp">6a.jp</a>">`

Expected: step 2のソースと同様の表示がされる。

FYI: 
以下は rainier テーマの例です

`<mt:If tag="BlogDescription"><meta name="description" content="<$mt:BlogDescription remove_html="1" encode_html="1"$>"></mt:If>`

**Comment by wtnbtkfm** [comment]
@cmatsuo 

各ページを修正しましたのでご確認よろしくお願いします。

**Comment by cmatsuo** [comment]
修正を確認。
