### ISSUE TITLE
テーマの一覧のサムネイル

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#27]
せっかくなので、Simple Corporateの参考画像のサムネイルが表示されるようにしましょう。

![theme](https://cloud.githubusercontent.com/assets/546386/21967203/c80ecb9c-dbc5-11e6-86f0-19f5a30ed51a.jpg)

**Comment by wtnbtkfm** [comment]
@cmatsuo 

サムネイルを設定しました。
ご確認お願いします。

**Comment by cmatsuo** [comment]
修正を確認しました。
