### ISSUE TITLE
ダイナミックパブリッシングの場合、ソースに改行が入る

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#28]
Simple Corporate テーマをダイナミックで公開した場合のソースを見ると、添付画像のように、上のほうにかなりの数の改行が入るのですが、これはなんでなんですかね？

![blank](https://cloud.githubusercontent.com/assets/546386/21967869/e6e3433e-dbd1-11e6-9973-2fa373b2e500.jpg)

**Comment by wtnbtkfm** [comment]
@cmatsuo 

これですが、テンプレートモジュールを読み込んでいるところに空行が挿入されてしまうようです。

**Comment by cmatsuo** [comment]
解消したようなので、クローズ。
