### ISSUE TITLE
各インデックス、アーカイブのdescriptionの表示について

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#29]
月別アーカイブとカテゴリ別アーカイブのブログの説明は、固定で以下のような表示になります。

`<meta property="og:description" content="（ブログ名）のニュース。（カテゴリ名）カテゴリのアーカイブページです。">`

他のアーカイブでは、meta description CF等で設定するか、CFで設定していない場合管理画面のブログの全般設定での設定内容が表示されるという動作になるのですが、ここも他のアーカイブに合わせるのはいかがでしょうか？

**Comment by wtnbtkfm** [comment]
@cmatsuo 

カテゴリアーカイブは、カテゴリの「説明」に入力されている場合はそれを。ない場合は
<meta property="og:description" content="（ブログ名）のニュース。（カテゴリ名）カテゴリのアーカイブページです。">
となるように修正しました。

年別アーカイブはmeta description CFに入力されていたらそれを。ない場合は
<meta property="og:description" content="（ブログ名）のニュース。◯◯年のアーカイブページです。">
となるように修正しました。

ご確認お願いします。

**Comment by cmatsuo** [comment]
@wtnbtkfm 素朴な疑問ですが、年別やカテゴリアーカイブでのみ、他のアーカイブと違って、独自の設定がない場合にも、ブログの管理画面での設定内容を表示させないのはどういった理由でしょうか？

**Comment by wtnbtkfm** [comment]
@cmatsuo 

すいません。上記のコメントでhtmlタグを記述した部分が消えてしまっていました。
正しくは以下になります。

-------------------------------------------------------------------------

カテゴリアーカイブは、カテゴリの「説明」に入力されている場合はそれを。ない場合は
`<meta property="og:description" content="（ブログ名）のニュース。（カテゴリ名）カテゴリのアーカイブページです。">`
となるように修正しました。

年別アーカイブはmeta description CFに入力されていたらそれを。ない場合は
`<meta property="og:description" content="（ブログ名）のニュース。◯◯年のアーカイブページです。">`
となるように修正しました。

------------------------------------------------------------------------- 

で、松尾さんが仰っている「ブログの管理画面での設定内容を表示させないのはどういった理由でしょうか？」ですが、全般設定の「説明」のことでしょうか？
meta descriptionはseo上、全ページ固有のものになっているのが望ましいので、ユーザーが特に意識しなくても全ページ固有になるように現在のような仕様にしてあります。

**Comment by cmatsuo** [comment]
@wtnbtkfm いや、つまり、「（ブログ名）のニュース。◯◯年のアーカイブページです。」というような表示が、SEOとしてベターだというのがよくわからなかったのですが。SEO的にそういうのもなんですか？

**Comment by wtnbtkfm** [comment]
@cmatsuo 
全ページのmeta descriptionを固有にしようとした時、年別アーカイブや月別アーカイブなどはユーザーが個別に設定する術が基本的にはないので、「（ブログ名）のニュース。◯◯年のアーカイブページです。」のように自動的に出力するというのはよくやります。
特に代理店が絡んでいて、かつSEO会社も絡んでがちがちにSEOまわりの実装をやらされる時は、こういう指定になることが多いですね。

ただ、「（ブログ名）のニュース。◯◯年のアーカイブページです。」これが最適か？と言われると難しいですね。あくまで各ページ固有にするために年別アーカイブや月別アーカイブで出来ることをやるとこんな感じになります。

あまり細かいことを気にしない案件だと、年別アーカイブや月別アーカイブのmeta descriptionはブログTOPのmeta descriptionと一緒でOK、となる場合も多いです。

もし松尾さん的にこうなっているのがベストだ、というものがあったらお教え頂ければ、それで調整することも可能だと思います。

**Comment by cmatsuo** [comment]
@wtnbtkfm 何がベストかはそのサイトによると思うのでわかりませんが、このテーマの場合、meta descriptionやカスタムフィールドで設定できるようになっているのだから、あえてそれらを設定しないような場合は、「（ブログ名）のニュース。◯◯年のアーカイブページです。」のような、サイト内以外では意味をなさない説明よりは、他のアーカイブ同様、サイト全体の説明（ブログの管理画面での説明）が入っているほうがベターではないのかなと思ったのでした。

**Comment by wtnbtkfm** [comment]
@cmatsuo 
どちらかというと、記事詳細でmeta description用のカスタムフィールドに入力されていない場合、サイト全体の説明文が出てしまうという方が間違えていますね。
記事詳細をmeta description用のカスタムフィールドが入力されていない場合は本文から120文字ほど抽出する、という風に修正するということでいかがでしょうか？
年別アーカイブはこのままで。

**Comment by cmatsuo** [comment]
@wtnbtkfm 
間違いですか。
そういうことであれば、チケットが複数になると面倒なので、他のページの仕様についてもここで決めるということでお願いします。
以下の各ページで、meta descriptionの設定がなかった場合、何を表示するのが仕様になるのか、まとめてお知らせください。

* インデックス
* ニュースTOP
* ウェブページアーカイブ
* 記事アーカイブ
* カテゴリ別アーカイブ
* 年別アーカイブ

FYI： 内容の変更に伴い、チケットのタイトルを変更しました。

**Comment by wtnbtkfm** [comment]
@cmatsuo 

修正しpushしました。再度pullお願いします。ウェブページと記事アーカイブを直してあります。
meta descrriptionの設定を下記にまとめます。

●インデックス
テンプレートのCFに入力されている場合はそれが、入力されていない場合はmt:blogdescriptionが表示されます。

●ニュースTOP
テンプレートのCFに入力されている場合にはそれが、入力されていない場合はmt:blogdescriptionが表示されます。

●ウェブページアーカイブ
ウェブページのCFに入力されている場合にはそれが、入力されていない場合は本文がremove_htmlされた上で、120文字抽出され表示されます。

●記事アーカイブ
記事のCFに入力されている場合にはそれが、入力されていない場合は本文がremove_htmlされた上で、120文字抽出され表示されます。

●カテゴリ別アーカイブ
カテゴリの「説明」に入力されている場合はそれが、入力されていない場合は
[ブログ名]のニュース。[カテゴリラベル]カテゴリのアーカイブページです。
が表示されます。

●年別アーカイブ
テンプレートのCFに入力されている場合はそれが、入力されていない場合は
[ブログ名]のニュース。◯◯年のアーカイブページです。
が表示されます。

**Comment by cmatsuo** [comment]
@wtnbtkfm 
記事アーカイブのCFにdescriptionが入力されている場合、ウェブページアーカイブのdescriptionが表示されます。

それ以外は、上記の通りの表示となることを確認。

**Comment by wtnbtkfm** [comment]
@cmatsuo 

> 記事アーカイブのCFにdescriptionが入力されている場合、ウェブページアーカイブのdescriptionが表示されます。

こちら、いまいち把握できていないのですが、
記事はテンプレートのCFではなく、記事自体の「meta description」フィールドに入力されている場合はそれが、ない場合は本文から120文字が抽出されるようになっています。

**Comment by cmatsuo** [comment]
いや、単なる確認ミスだった。クローズ！
