### ISSUE TITLE
テンプレートモジュールの表記について

### ISSUE THREAD

**Issue by crawl749** [movabletype/mt-theme-SimpleCorporate#30]
テンプレートモジュールの名称が現状英語表記ですが、テンプレートモジュール名だけが英語表記なのが違和感があります。
（js、css、configは除く）
日本語表記に変更しませんか？

**Comment by yuji** [comment]
修正が落ち着いたら時間のあるときにL10Nするので。

**Comment by yuji** [comment]
Next!

**Comment by yuji** [comment]
https://github.com/movabletype/mt-theme-SimpleCorporate/commit/e8f6a5f50d7b1a1c4dc00184336c81cb6be2d228

**Comment by crawl749** [comment]
かくにんできたのでとじます
