### ISSUE TITLE
indexにMTPageBodyがないのはなぜ？

### ISSUE THREAD

**Issue by crawl749** [movabletype/mt-theme-SimpleCorporate#31]
今更で申し訳ないないのですが、indexのテンプレートを見ていてMTPageBodyがない事に気づきました。
これはわざと外しているという事なんでしょうか？
わざとなら理由を教えていただけるとうれしいです。

**Comment by crawl749** [comment]
今更で申し訳ないないのですが、indexのテンプレートを見ていてMTPageBodyがない事に気づきました。
これはわざと外しているという事なんでしょうか？
わざとなら理由を教えていただけるとうれしいです。

**Comment by wtnbtkfm** [comment]
@crawl749 

#21で修正しました。
概要がない場合は、MTPageBodyが表示されるように修正してあります。

**Comment by crawl749** [comment]
確認できたのでクローズ
