### ISSUE TITLE
ブログでテーマが表示されなくなった

### ISSUE THREAD

**Issue by crawl749** [movabletype/mt-theme-SimpleCorporate#32]
今までウェブサイト、ブログ両方で利用可能なテーマ一覧に表示されていたのですが、
今回のアップデートで表示されなくなり、ブログに適用できなくなったのですが、
これは意図的にそうしたのでしょうか？

**Comment by wtnbtkfm** [comment]
@crawl749 

おそらくtheme.yamlの
class: website
という設定の部分のせいだと思います。
今のこちらの環境でテーマをエクスポートすると、class: websiteになってしまうんですよね。。。

theme.yamlをテーマを修正してエクスポートする度に直すのがかなり手間だったため、
theme.yamlの修正はテンプレートまわりの修正が一通り収束したら行うつもりでいました。

**Comment by crawl749** [comment]
@wtnbtkfm 
申し訳ないんですが、QAしづらいんで、こういうところだけは直していただけるとうれしいのですが。

**Comment by wtnbtkfm** [comment]
@crawl749 

承知しました。以降pushする時はこの部分を修正します。
取り急ぎtheme.yamlを修正してpushしました。

**Comment by crawl749** [comment]
ブログでも適用できるようになったのでとじます
