### ISSUE TITLE
フッターのコピーライト表記について

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#35]
@yuji 
MTに同梱のテーマの場合、コピーライトというよりは、「Powered by Movable Type」という表示で、会社のMTのページにリンクがあるような表示をしているのですが、このテーマでは、特にリンクなどは無しで、「©Six Apart Ltd.」となっています。
同梱のテーマとは違うということで、意図的にこのテーマに関してはこの形の表示がいいということになるのでしょうか？
判断が付きかねるので、今後のためのテーマ作成時の仕様として、どうあるべきなのか決めてしまっていただけるとありがたいです。

* Classic Themeのフッター
![class](https://cloud.githubusercontent.com/assets/546386/22581418/21cc32e4-ea23-11e6-8def-522f2ca17bd7.jpg)

* SimpleCorporateのフッター
![sc](https://cloud.githubusercontent.com/assets/546386/22581427/353e7d1e-ea23-11e6-8de3-673af0a00a85.jpg)

**Comment by yuji** [comment]
@cmatsuo 
@wtnbtkfm 

ライセンス的には MIT にしているけど、Copyright 表記があるとテーマを改変できないみたいに見えちゃうので

<__trans phrase="_POWERED_BY">

これにしておいたほうがいいかな。

**Comment by wtnbtkfm** [comment]
@cmatsuo 
@yuji 

copyrightを
`Powered by <a href="http://www.sixapart.jp/movabletype/">Movable Type Pro</a>`
に変更しました。
ご確認お願いします。

**Comment by yuji** [comment]
@wtnbtkfm 

必ずしも Movable Type Pro とも限らないので、

<__trans phrase="_POWERED_BY">

これでお願いします。
テーマ適用時にいい感じに

    'Powered by <a href="http://www.sixapart.jp/movabletype/"><$MTProductName$></a>',

こんな感じで処理されるんで。

**Comment by wtnbtkfm** [comment]
@yuji 

おお、承知しました。
修正します。

**Comment by wtnbtkfm** [comment]
@cmatsuo 

高山さんがご指摘の件、修正しましたので再度pullっていただきご確認お願いします。

**Comment by cmatsuo** [comment]
確認したのでクローズ。
