### ISSUE TITLE
テーマをあてると概要（ページ）のCFが作成される

### ISSUE THREAD

**Issue by crawl749** [movabletype/mt-theme-SimpleCorporate#36]
<img width="825" alt="2017-02-03 15 39 38" src="https://cloud.githubusercontent.com/assets/546365/22581954/0fe6d710-ea27-11e6-9eef-227422dd7a17.png">

テーマをあてると概要（ページ）のCFが作成され、MTに元々ある概要と混乱してしまう。
テーマをあてた際にできた”概要”は何に使われるものなのでしょうか？
MTに元々ある”概要”と混乱してしまうので、必要な場合はリネームしていただけないでしょうか？

**Comment by wtnbtkfm** [comment]
@crawl749 

過去に使っていたCFが残ってしまっていたようです。
こちらはもう必要のないものですので削除しました。

**Comment by crawl749** [comment]
修正を確認できたので閉じます
