### ISSUE TITLE
サイトロゴのデフォルト画像の差し替え

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-SimpleCorporate#37]
SAのロゴが使われているのはよろしくないので、.net で使われているロゴに差し替え願います。

https://theme.movabletype.io/simplecorporate/

**Comment by wtnbtkfm** [comment]
@yuji 

.netで使われているロゴに修正しました。
ご確認お願いします。

**Comment by yuji** [comment]
Okay
