### ISSUE TITLE
使っていないテンプレートの内容

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-SimpleCorporate#38]
#20 で使わない人は無視でいんじゃないと言いましたが、枠だけ作ってあげて中身はナシでいんじゃない。という意味でした。存在しないモジュールや、合っていない構造だとツラ伊野ではないかと思うので、デフォルトは空っぽでいんじゃないかと思いますが、どうでしょ？

**Comment by wtnbtkfm** [comment]
@yuji 

ご指摘の通り空っぽにしておくのが一番合理的だと思いますので空っぽにしました。

**Comment by yuji** [comment]
Okay
