### ISSUE TITLE
common.js のリンク

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-SimpleCorporate#39]
<script src="<mt:blogrelativeurl>/common.js"></script>
となっていますが、<MTLink template="common.js"> だとファイル名やパスの変更にも追随できるので良いのではないかと思うのですが、どうでしょ？

**Comment by wtnbtkfm** [comment]
@yuji 

上記のタグの部分が消えてしまっているようなのですが、
`<script src="/common.js">`
を
`<mt:Link template="common.js" encode_html="1">`
に修正するということで間違いないでしょうか？
問題なければこちらに修正します！

**Comment by yuji** [comment]
@wtnbtkfm 

おっとい、preするの忘れてた。MTLInkで！

**Comment by wtnbtkfm** [comment]
@yuji 

該当箇所を
`<script src="<mt:Link template="common.js" encode_html="1">"></script>`
に修正しました！
ご確認お願いします。

**Comment by yuji** [comment]
Okay
