### ISSUE TITLE
metakeywords の初期値が適切ではない

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-SimpleCorporate#40]
<mt:setvarblock name="metakeywords">movable type,mt,テーマ,theme,</mt:setvarblock>

カスタマイズガイドでここで変えられるよ。と説明して変更できるようにするということではありますが、そのままビルドした結果でこれがでるのは適切ではないかなあ。

**Comment by wtnbtkfm** [comment]
@yuji 

デフォルトをブログ名とウェブページの一覧が表示されるように
`<mt:setvarblock name="metakeywords"><mt:blogname>,<mt:pages><mt:pagetitle>,</mt:pages></mt:setvarblock>`
この形に修正しました。

**Comment by yuji** [comment]
Okay
