### ISSUE TITLE
facebook の初期値

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-SimpleCorporate#41]
<mt:setvarblock name="facebook">https://www.facebook.com/sixapartkk</mt:setvarblock>                                                                  

SAを向いているのは好ましくないので xxxxxx とかにしたほうがいいかな。

**Comment by wtnbtkfm** [comment]
@yuji 

`<mt:setvarblock name="facebook">xxxxxx</mt:setvarblock>`
に修正しました。ご確認お願いします。

**Comment by yuji** [comment]
Okay
