### ISSUE TITLE
twitter の初期値

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-SimpleCorporate#42]
<mt:setvarblock name="twitter">https://twitter.com/movabletypejp</mt:setvarblock> 

MTを向いているのは好ましくないので xxxxx とかかな。

**Comment by yuji** [comment]
<mt:SetVarBlock name="twitterVia">movabletype</mt:SetVarBlock> 
ここもだね

**Comment by wtnbtkfm** [comment]
@yuji 

上記の2箇所を
`<mt:setvarblock name="twitter">xxxxxx</mt:setvarblock>`
`<mt:SetVarBlock name="twitterVia"></mt:SetVarBlock>`
に修正しました。
twitterViaは設定されていなくても特に問題はないので空にしてあります。

**Comment by yuji** [comment]
Okay
