### ISSUE TITLE
Google+ の初期値

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-SimpleCorporate#43]
<mt:setvarblock name="google">https://hogehoge</mt:setvarblock>

hogehogeはちょっとｗ

https://plus.google.com/xxxxx とかかな

**Comment by wtnbtkfm** [comment]
@yuji 

仮で設定したものがそのままになっていました。。。
`<mt:setvarblock name="google">xxxxxx</mt:setvarblock>`
に修正してあります。ご確認お願いします。

**Comment by yuji** [comment]
Okay
