### ISSUE TITLE
【css】bgのパスが//になっている

### ISSUE THREAD

**Issue by crawl749** [movabletype/mt-theme-SimpleCorporate#5]
cssの195行目くらい

> background: url(<mt:if name="main-bg"><mt:assets type="image" tag="@MAIN_BACKGROUND" limit="1"><mt:assetthumbnailurl></mt:assets><mt:else><mt:blogrelativeurl>/images/bg-top-main.png</mt:if>) no-repeat center bottom;

が出力されると以下のようになっています。

background: url(/simple_corporate//images/bg-top-main.png) no-repeat center bottom;

//にならないように修正お願いします。

**Comment by wtnbtkfm** [comment]
@crawl749 
修正しpushしました。
こちらで再度ご確認お願いします。

**Comment by crawl749** [comment]
修正確認できたのでクローズします。
