### ISSUE TITLE
【css】@MAIN_BACKGROUNDのbg指定について

### ISSUE THREAD

**Issue by crawl749** [movabletype/mt-theme-SimpleCorporate#6]
スタイルシートLOWER CONTENT部分についてです。

> <mt:if name="main-bg"><mt:assets tag="@MAIN_BACKGROUND" limit="1"><mt:assetthumbnailurl></mt:assets></mt:if>
> 
> #mainvisual-lower {
> position: relative;
> padding: 3.5em 0;
> background: url(<mt:if name="main-bg"><mt:assets type="image" tag="@MAIN_BACKGROUND" limit="1"><mt:assetthumbnailurl></mt:assets><mt:else><mt:blogrelativeurl>/images/bg-top-main.png</mt:if>) no-repeat center bottom;
> background-size: cover;
> color: #fff;
> text-shadow: 0 1px 0px #000;
> }

のbg画像指定についてですが、現状、bg-top-main.png以外の画像にシークレットタグをつけても全く認識せずなので、試しに

> <mt:if name="main-bg"><mt:assets type="image" tag="@MAIN_BACKGROUND" limit="1"><mt:assetthumbnailurl></mt:assets><mt:else><mt:blogrelativeurl>/images/bg-top-main.png</mt:if>

だけを別テンプレートに貼り付け出力してみたところ、以下のような出力結果となりました。

> https://mtqa5.movabletype.biz/simple_corporate/assets_c/2016/12/pic-thumb-1080x1080-15.jpg/simple_corporate//images/bg-top-main.png

<mt:else>の部分が正常に動作していないように見えるのですが、
cssはシークレットタグが設定されていようといなかろうと、出力結果は

> background: url(/simple_corporate//images/bg-top-main.png) no-repeat center bottom;

となっているので、シークレットタグ（またはmtタグ？）を認識できていないように見えます。

**Comment by crawl749** [comment]
TOPのbg指定のところも同様に。

**Comment by wtnbtkfm** [comment]
@crawl749 
こちら正常にsetvar出来ていないバグでした。
お手数おかけしてしまい申し訳ありません。
修正しpushしましたので再度ご確認お願いします。

**Comment by crawl749** [comment]
修正確認できたのでクローズします。
