### ISSUE TITLE
【質問】キービジュアルのファイル名が固定されている

### ISSUE THREAD

**Issue by crawl749** [movabletype/mt-theme-SimpleCorporate#7]
キービジュアルのファイル名が固定なのはなぜでしょうか？
アセットにシークレットタグで指定、というふうにはできないものでしょうか？

**Comment by wtnbtkfm** [comment]
シークレットタグを使って実装することは可能です。
今ファイル名が固定になってしまっているのは.netのテーマにする時の名残ですので、修正しますね。
修正後、改めてこちらでご報告します。

**Comment by wtnbtkfm** [comment]
@crawl749 
アセットにシークレットタグ「@MAIN_IMAGE」を付与することで差し替えることができるようにしました。
pushしてありますのでご確認お願いします。

**Comment by crawl749** [comment]
「@MAIN_IMAGE」で差し替えられることを確認したので閉じます
