### ISSUE TITLE
Chrome: Faviconの削除ができない

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#8]
Steps:
0. 以下、Chromeで確認。
1. アップロードした画像に、シークレットタグ「@SITE_FAVICON」を付与して、再構築。
2. 公開したブログで、favicon が設定した通り表示されていることを確認。
3. 1でアップロードした画像の編集画面で、シークレットタグ「@SITE_FAVICON」を削除して、再構築。
4. 公開したブログで、favicon を確認。

Expected: favicon が表示されなくなっている
Observed: 1で設定した favicon が表示されている

FYI: 他のブラウザ、FFやSafariでは、予想通り、表示されないという動作。
FYI2: ブラウザキャッシュとしか思えないが、しかしChromeではブラウザのキャッシュを消しても、タグ削除前の favicon が表示されつづける。
FYI3: Chromeでも、他の 画像に変更することはできる。

**Comment by wtnbtkfm** [comment]
Chromeでは、履歴を削除しただけではfaviconが更新されないようです。

http://qiita.com/chocodoughnut/items/691a4a768124028bedb5
http://paivittain-kukka.com/chrome-favicon/

こちらはMTからはコントロール出来ないと思われるので、上記の手順で再度ご確認いただいてもよろしいでしょうか。

**Comment by cmatsuo** [comment]
確認できました。
