### ISSUE TITLE
カテゴリ数が多いと、プルダウンメニューにすべてのカテゴリのリンクを表示することができない

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/mt-theme-SimpleCorporate#9]
参考まで。添付画像のブログではカテゴリが28あるが、ブラウザのスクロールバーなどを使っても、16個目あたり以降を表示することができない。（Chrome, FF, Safari, Edgeで同様）

![menu](https://cloud.githubusercontent.com/assets/546386/21339998/dc8a1572-c6c6-11e6-894f-27442d3ed266.jpg)

**Comment by wtnbtkfm** [comment]
@cmatsuo 
ドロップダウンメニューの高さを最大400px（スマホビューは200px）とし、それを超える場合はスクロールバーが出るように修正し、pushしました。
こちらで再度ご確認お願いします。

**Comment by cmatsuo** [comment]
スクロールバーで表示できるようになったことを確認しました。
